// Principais municípios brasileiros — usado para autocomplete de local em vagas
export const CITIES = [
  'Abreu e Lima, PE','Alagoinhas, BA','Alvorada, RS','Americana, SP','Ananindeua, PA',
  'Anápolis, GO','Aparecida de Goiânia, GO','Aracaju, SE','Araçatuba, SP','Araguaína, TO',
  'Araraquara, SP','Barueri, SP','Bauru, SP','Belém, PA','Belo Horizonte, MG',
  'Betim, MG','Blumenau, SC','Boa Vista, RR','Brasília, DF','Camaçari, BA',
  'Campina Grande, PB','Campinas, SP','Campo Grande, MS','Campo Largo, PR','Canoas, RS',
  'Carapicuíba, SP','Caruaru, PE','Cascavel, PR','Caucaia, CE','Caxias do Sul, RS',
  'Chapecó, SC','Cidade de Deus, RJ','Contagem, MG','Cotia, SP','Cuiabá, MT',
  'Curitiba, PR','Diadema, SP','Dourados, MS','Duque de Caxias, RJ','Embu das Artes, SP',
  'Feira de Santana, BA','Florianópolis, SC','Fortaleza, CE','Foz do Iguaçu, PR',
  'Franca, SP','Goiânia, GO','Governador Valadares, MG','Gravataí, RS','Guarujá, SP',
  'Guarulhos, SP','Ilhéus, BA','Imperatriz, MA','Indaiatuba, SP','Ipatinga, MG',
  'Itabuna, BA','Jaboatão dos Guararapes, PE','Jequié, BA','João Pessoa, PB',
  'Joinville, SC','Juazeiro do Norte, CE','Juiz de Fora, MG','Jundiaí, SP',
  'Lauro de Freitas, BA','Limeira, SP','Londrina, PR','Luziânia, GO','Macapá, AP',
  'Maceió, AL','Manaus, AM','Marabá, PA','Maricá, RJ','Maringá, PR','Marília, SP',
  'Mauá, SP','Mogi das Cruzes, SP','Montes Claros, MG','Mossoró, RN','Natal, RN',
  'Niterói, RJ','Nova Friburgo, RJ','Nova Iguaçu, RJ','Novo Hamburgo, RS',
  'Olinda, PE','Osasco, SP','Palmas, TO','Parnaíba, PI','Paulista, PE','Pelotas, RS',
  'Petrolina, PE','Petrópolis, RJ','Piracicaba, SP','Porto Alegre, RS','Porto Velho, RO',
  'Praia Grande, SP','Recife, PE','Ribeirão das Neves, MG','Ribeirão Preto, SP',
  'Rio Branco, AC','Rio de Janeiro, RJ','Rondonópolis, MT','Salvador, BA',
  'Santa Luzia, MG','Santa Maria, RS','Santarém, PA','Santo André, SP',
  'Santos, SP','São Bernardo do Campo, SP','São Gonçalo, RJ','São João de Meriti, RJ',
  'São José, SC','São José do Rio Preto, SP','São José dos Campos, SP','São Luís, MA',
  'São Paulo, SP','Serra, ES','Sorocaba, SP','Sobral, CE','Sumaré, SP',
  'Suzano, SP','Taboão da Serra, SP','Teresina, PI','Teresópolis, RJ','Uberaba, MG',
  'Uberlândia, MG','Várzea Grande, MT','Viamão, RS','Vila Velha, ES','Vitória, ES',
  'Vitória da Conquista, BA','Volta Redonda, RJ',
  // Capitais e cidades turísticas menores
  'Altamira, PA','Aracruz, ES','Arraial do Cabo, RJ','Armação dos Búzios, RJ',
  'Balneário Camboriú, SC','Bento Gonçalves, RS','Bonito, MS','Campos do Jordão, SP',
  'Campos dos Goytacazes, RJ','Confins, MG','Criciúma, SC','Cruz das Almas, BA',
  'Diamantina, MG','Eunápolis, BA','Fernando de Noronha, PE','Floriano, PI',
  'Garanhuns, PE','Ilhabela, SP','Ilhéus, BA','Itajaí, SC','Itaparica, BA',
  'Itapetininga, SP','Itaquaquecetuba, SP','Itumbiara, GO','Jaraguá do Sul, SC',
  'Lajeado, RS','Lages, SC','Lagoa Santa, MG','Linhares, ES','Macaé, RJ',
  'Manhuaçu, MG','Maracanaú, CE','Natal, RN','Palhoça, SC','Parauapebas, PA',
  'Passos, MG','Passo Fundo, RS','Patos de Minas, MG','Paulínia, SP','Penedo, AL',
  'Piauí, PI','Pinhais, PR','Ponta Grossa, PR','Porto Seguro, BA','Presidente Prudente, SP',
  'Rio Claro, SP','Rio Verde, GO','Russas, CE','São Carlos, SP','São Mateus, ES',
  'São Paulo, SP','Sete Lagoas, MG','Sinop, MT','Taubaté, SP','Ubá, MG',
  'Varginha, MG','Viana, ES',
];
